#!/bin/bash

outdir="./../../../shiri_server/shiri_common/"
npx tsc ./gamemodes.tsx -d -m commonjs --downlevelIteration --importHelpers --target es6 --esModuleInterop --outDir $outdir --jsx react
npx tsc ./errors.tsx -d -m commonjs --esModuleInterop --outDir $outdir  --jsx react